services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    depends_on:
      - ollama
    networks:
      - default
    ports:
      - "3000:8080"
    volumes:
      - $DOCKERDIR/appdata/open-webui:/app/backend/data
    environment:
      OLLAMA_BASE_URL: $OLLAMA_URL 
      WEBUI_SECRET_KEY: $WEBUI_SECRET_KEY
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  open-webui:
    name: open-webui
