services:
  audiobookshelf:
    image: advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - default
    ports:
      - "13378:80"
    volumes:
      - $DOCKERDIR/appdata/audiobookshelf/config:/config
      - $DOCKERDIR/appdata/audiobookshelf/metadata:/metadata
      - type: volume
        source: media
        target: /audiobooks
        volume:
          subpath: Books

      - type: volume
        source: media
        target: /podcasts
        volume:
          subpath: Podcasts
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
