services:
  # Listenarr - Audiobook management
  listenarr:
    image: docker.io/therobbiedavis/listenarr:canary
    container_name: listenarr
    security_opt:
      - no-new-privileges:true
    restart: "no"
    # profiles: ["media", "arrs", "all"]
    networks:
      - default
    ports:
      - "4545:4545"
    volumes:
      - $DOCKERDIR/appdata/listenarr:/config
      - type: volume
        source: media
        target: /audiobooks
        volume:
          subpath: Audiobooks

      - type: volume
        source: media
        target: /downloads
        volume:
          subpath: downloads
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
