services:
  # qBittorrent - BitTorrent client
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"   # Route all traffic through Gluetun
    depends_on:
      - gluetun
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      UMASK_SET: 002
      WEBUI_PORT: 8081                # qBittorrent listens on 8080 inside container
    volumes:
      - ${DOCKERDIR}/appdata/qbittorrent:/config
      - ${DATADIR}/downloads:/data/downloads
