services:
  # SABnzbd - Binary newsgrabber (NZB downloader)
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["apps", "downloads", "all"]
    volumes:
      - $DOCKERDIR/appdata/sabnzbd:/config
      - $DATADIR/downloads:/data/downloads
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      UMASK_SET: 002
